/*!40101 SET NAMES utf8mb4 */;
use user_management;

CREATE TABLE IF NOT EXISTS risk_month_end_batch (
  id bigint primary key auto_increment,
  batch_no varchar(64) not null,
  month_end_date date not null,
  source_data_date date not null,
  version_no int not null default 1,
  batch_type varchar(32) not null default 'MONTH_END',
  source_system varchar(64) not null default 'UPSTREAM_CREDIT',
  status varchar(32) not null default 'RECEIVED',
  published_flag tinyint not null default 0,
  locked_flag tinyint not null default 0,
  record_count int not null default 0,
  customer_count int not null default 0,
  total_ead decimal(20,2) not null default 0.00,
  total_el_avg decimal(20,2) not null default 0.00,
  total_el_downturn decimal(20,2) not null default 0.00,
  quality_score decimal(8,2) not null default 0.00,
  reconciliation_status varchar(32) not null default 'PENDING',
  failure_message varchar(1000),
  created_by varchar(100) not null,
  started_at datetime not null default current_timestamp,
  completed_at datetime,
  published_at datetime,
  created_at datetime not null default current_timestamp,
  updated_at datetime not null default current_timestamp on update current_timestamp,
  unique key uk_risk_month_end_batch_no (batch_no),
  unique key uk_risk_month_end_batch_version (month_end_date, version_no),
  key idx_risk_month_end_batch_status (status, month_end_date),
  constraint ck_risk_month_end_batch_version check (version_no > 0)
);

CREATE TABLE IF NOT EXISTS risk_month_end_exposure_snapshot (
  id bigint primary key auto_increment,
  batch_id bigint not null,
  month_end_date date not null,
  exposure_no varchar(32) not null,
  customer_no varchar(32) not null,
  customer_name varchar(200) not null,
  contract_no varchar(32) not null,
  debt_no varchar(32) not null,
  product_type varchar(64) not null,
  industry_name varchar(100),
  owner_org_name varchar(150),
  rating_result varchar(20),
  risk_level varchar(32),
  ead_amount decimal(20,2) not null default 0.00,
  pd decimal(10,6) not null default 0.000000,
  lgd_avg decimal(10,6) not null default 0.000000,
  lgd_downturn decimal(10,6) not null default 0.000000,
  el_avg decimal(20,2) not null default 0.00,
  el_downturn decimal(20,2) not null default 0.00,
  exposure_balance decimal(20,2) not null default 0.00,
  collateral_value decimal(20,2) not null default 0.00,
  product_recovery_rate decimal(10,6) not null default 0.000000,
  overdue_days int not null default 0,
  default_flag tinyint not null default 0,
  five_category varchar(32),
  model_name varchar(100),
  model_version varchar(64),
  created_at datetime not null default current_timestamp,
  unique key uk_risk_month_end_exposure (batch_id, exposure_no),
  key idx_risk_month_end_exposure_customer (batch_id, customer_no),
  key idx_risk_month_end_exposure_debt (batch_id, debt_no),
  key idx_risk_month_end_exposure_dimension (batch_id, industry_name, product_type),
  constraint fk_risk_month_end_exposure_batch foreign key (batch_id) references risk_month_end_batch(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS risk_month_end_customer_snapshot (
  id bigint primary key auto_increment,
  batch_id bigint not null,
  month_end_date date not null,
  customer_no varchar(32) not null,
  customer_name varchar(200) not null,
  industry_name varchar(100),
  owner_org_name varchar(150),
  rating_result varchar(20),
  risk_level varchar(32),
  active_debt_count int not null default 0,
  ead_amount decimal(20,2) not null default 0.00,
  weighted_pd decimal(10,6) not null default 0.000000,
  weighted_lgd_avg decimal(10,6) not null default 0.000000,
  weighted_lgd_downturn decimal(10,6) not null default 0.000000,
  el_avg_amount decimal(20,2) not null default 0.00,
  el_downturn_amount decimal(20,2) not null default 0.00,
  collateral_value decimal(20,2) not null default 0.00,
  overdue_count int not null default 0,
  max_overdue_days int not null default 0,
  default_debt_count int not null default 0,
  default_flag tinyint not null default 0,
  high_risk_flag tinyint not null default 0,
  created_at datetime not null default current_timestamp,
  unique key uk_risk_month_end_customer (batch_id, customer_no),
  key idx_risk_month_end_customer_risk (batch_id, risk_level, default_flag),
  constraint fk_risk_month_end_customer_batch foreign key (batch_id) references risk_month_end_batch(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS risk_month_end_summary (
  id bigint primary key auto_increment,
  batch_id bigint not null,
  month_end_date date not null,
  dimension_type varchar(32) not null,
  dimension_code varchar(160) not null,
  dimension_name varchar(160) not null,
  customer_count int not null default 0,
  exposure_count int not null default 0,
  high_risk_count int not null default 0,
  overdue_count int not null default 0,
  default_count int not null default 0,
  ead_amount decimal(20,2) not null default 0.00,
  weighted_pd decimal(10,6) not null default 0.000000,
  weighted_lgd_avg decimal(10,6) not null default 0.000000,
  weighted_lgd_downturn decimal(10,6) not null default 0.000000,
  el_avg_amount decimal(20,2) not null default 0.00,
  el_downturn_amount decimal(20,2) not null default 0.00,
  concentration_ratio decimal(10,6) not null default 0.000000,
  created_at datetime not null default current_timestamp,
  unique key uk_risk_month_end_summary_dimension (batch_id, dimension_type, dimension_code),
  key idx_risk_month_end_summary_type (dimension_type, month_end_date),
  constraint fk_risk_month_end_summary_batch foreign key (batch_id) references risk_month_end_batch(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS risk_month_end_change_detail (
  id bigint primary key auto_increment,
  current_batch_id bigint not null,
  base_batch_id bigint not null,
  grain_type varchar(32) not null default 'DEBT',
  business_key varchar(64) not null,
  customer_no varchar(32) not null,
  customer_name varchar(200),
  contract_no varchar(32),
  debt_no varchar(32),
  industry_name varchar(100),
  product_type varchar(64),
  previous_rating varchar(20),
  current_rating varchar(20),
  previous_risk_level varchar(32),
  current_risk_level varchar(32),
  previous_ead decimal(20,2) not null default 0.00,
  current_ead decimal(20,2) not null default 0.00,
  ead_delta decimal(20,2) not null default 0.00,
  previous_pd decimal(10,6) not null default 0.000000,
  current_pd decimal(10,6) not null default 0.000000,
  pd_delta decimal(10,6) not null default 0.000000,
  previous_lgd decimal(10,6) not null default 0.000000,
  current_lgd decimal(10,6) not null default 0.000000,
  lgd_delta decimal(10,6) not null default 0.000000,
  previous_el decimal(20,2) not null default 0.00,
  current_el decimal(20,2) not null default 0.00,
  el_delta decimal(20,2) not null default 0.00,
  previous_overdue_days int not null default 0,
  current_overdue_days int not null default 0,
  previous_default_flag tinyint not null default 0,
  current_default_flag tinyint not null default 0,
  change_type varchar(32) not null,
  reason_code varchar(64) not null,
  created_at datetime not null default current_timestamp,
  unique key uk_risk_month_end_change_pair (current_batch_id, base_batch_id, grain_type, business_key),
  key idx_risk_month_end_change_type (current_batch_id, base_batch_id, change_type),
  key idx_risk_month_end_change_customer (current_batch_id, base_batch_id, customer_no),
  constraint fk_risk_month_end_change_current foreign key (current_batch_id) references risk_month_end_batch(id) on delete cascade,
  constraint fk_risk_month_end_change_base foreign key (base_batch_id) references risk_month_end_batch(id) on delete cascade
);

CREATE TABLE IF NOT EXISTS risk_month_end_reconciliation (
  id bigint primary key auto_increment,
  batch_id bigint not null,
  check_code varchar(64) not null,
  check_name varchar(200) not null,
  source_value decimal(24,6) not null default 0.000000,
  snapshot_value decimal(24,6) not null default 0.000000,
  difference_value decimal(24,6) not null default 0.000000,
  tolerance_value decimal(24,6) not null default 0.000000,
  check_status varchar(32) not null,
  detail_message varchar(500),
  created_at datetime not null default current_timestamp,
  unique key uk_risk_month_end_reconciliation (batch_id, check_code),
  key idx_risk_month_end_reconciliation_status (check_status, created_at),
  constraint fk_risk_month_end_reconciliation_batch foreign key (batch_id) references risk_month_end_batch(id) on delete cascade
);
