use user_management;

create table if not exists corporate_credit_application (
  id bigint unsigned not null auto_increment,
  tenant_id bigint not null default 1,
  application_no varchar(32) not null,
  customer_id bigint unsigned not null,
  customer_no_snapshot varchar(32) not null,
  customer_name_snapshot varchar(200) not null,
  application_type varchar(32) not null default 'NEW_LIMIT',
  product_type varchar(64) not null,
  related_limit_id bigint unsigned,
  currency varchar(8) not null default 'CNY',
  apply_amount decimal(18,2) not null default 0.00,
  apply_term_months int,
  apply_rate decimal(8,4),
  repayment_method varchar(64),
  fund_usage varchar(300),
  guarantee_type varchar(64),
  collateral_desc varchar(500),
  guarantor_desc varchar(500),
  latest_rating_level varchar(20),
  customer_risk_level varchar(32),
  risk_assessment_result varchar(32),
  risk_assessment_remark text,
  application_status varchar(32) not null default 'DRAFT',
  submitted_at datetime,
  approved_at datetime,
  rejected_at datetime,
  applicant_id bigint unsigned,
  applicant_name varchar(100),
  manager_id bigint unsigned,
  manager_name varchar(100),
  owner_org_id bigint unsigned,
  owner_org_name varchar(150),
  approval_no varchar(64),
  approval_opinion text,
  document_list_json json,
  application_detail_json json,
  remark varchar(500),
  created_by bigint unsigned,
  created_by_name varchar(100),
  created_at datetime not null default current_timestamp,
  updated_by bigint unsigned,
  updated_by_name varchar(100),
  updated_at datetime not null default current_timestamp on update current_timestamp,
  deleted_flag tinyint not null default 0,
  primary key (id),
  unique key uk_corporate_credit_application_no (application_no),
  key idx_corporate_credit_application_customer (customer_id),
  key idx_corporate_credit_application_customer_no (customer_no_snapshot),
  key idx_corporate_credit_application_limit (related_limit_id),
  key idx_corporate_credit_application_status (application_status),
  key idx_corporate_credit_application_type (application_type),
  key idx_corporate_credit_application_org (owner_org_id),
  key idx_corporate_credit_application_created_at (created_at),
  constraint fk_corporate_credit_application_customer
    foreign key (customer_id) references corporate_customer (id),
  constraint fk_corporate_credit_application_customer_no
    foreign key (customer_no_snapshot) references corporate_customer (customer_no),
  constraint fk_corporate_credit_application_limit
    foreign key (related_limit_id) references corporate_credit_limit (id),
  constraint ck_corporate_credit_application_amount
    check (apply_amount >= 0)
);
