use user_management;

create table if not exists corporate_customer (
  id bigint unsigned not null auto_increment,
  tenant_id bigint not null default 1,
  customer_no varchar(32) not null,
  customer_name varchar(200) not null,
  customer_short_name varchar(100),
  unified_social_credit_code varchar(18),
  registration_no varchar(64),
  taxpayer_no varchar(64),
  company_type varchar(50),
  industry_code varchar(32),
  industry_name varchar(100),
  registered_capital decimal(18,2),
  capital_currency varchar(8) default 'CNY',
  established_date date,
  business_term_start date,
  business_term_end date,
  registered_address varchar(300),
  business_address varchar(300),
  business_scope text,
  legal_representative_name varchar(100),
  legal_representative_id_type varchar(32),
  legal_representative_id_no_enc varchar(512),
  legal_representative_id_no_hash varchar(128),
  contact_name varchar(100),
  contact_title varchar(100),
  contact_mobile varchar(32),
  contact_phone varchar(32),
  contact_email varchar(128),
  bank_name varchar(150),
  bank_branch_name varchar(150),
  bank_account_name varchar(200),
  bank_account_no_enc varchar(512),
  bank_account_no_hash varchar(128),
  customer_type varchar(32) default 'NORMAL',
  customer_level varchar(32),
  source_channel varchar(64),
  relationship_manager_id bigint unsigned,
  relationship_manager_name varchar(100),
  owner_org_id bigint unsigned,
  owner_org_name varchar(150),
  kyc_status varchar(32) not null default 'PENDING',
  risk_level varchar(32) default 'LOW',
  blacklist_flag tinyint not null default 0,
  compliance_remark varchar(500),
  status varchar(32) not null default 'ACTIVE',
  remark varchar(500),
  created_by bigint unsigned,
  created_by_name varchar(100),
  created_at datetime not null default current_timestamp,
  updated_by bigint unsigned,
  updated_by_name varchar(100),
  updated_at datetime not null default current_timestamp on update current_timestamp,
  deleted_flag tinyint not null default 0,
  primary key (id),
  unique key uk_corporate_customer_no (customer_no),
  unique key uk_corporate_customer_credit_code (unified_social_credit_code),
  key idx_corporate_customer_name (customer_name),
  key idx_corporate_customer_mobile (contact_mobile),
  key idx_corporate_customer_legal_hash (legal_representative_id_no_hash),
  key idx_corporate_customer_bank_hash (bank_account_no_hash),
  key idx_corporate_customer_kyc (kyc_status),
  key idx_corporate_customer_risk (risk_level),
  key idx_corporate_customer_status (status),
  key idx_corporate_customer_org (owner_org_id),
  key idx_corporate_customer_created_at (created_at)
);
