use user_management;

create table if not exists corporate_rating (
  id bigint unsigned not null auto_increment,
  tenant_id bigint not null default 1,
  rating_no varchar(32) not null,
  customer_id bigint unsigned not null,
  customer_no_snapshot varchar(32) not null,
  customer_name_snapshot varchar(200) not null,
  rating_type varchar(32) not null default 'REGULAR',
  rating_source varchar(32) not null default 'MANUAL',
  rating_model varchar(32) not null default 'INTERNAL',
  quantitative_score decimal(8,2),
  qualitative_score decimal(8,2),
  rating_score decimal(8,2),
  rating_level varchar(20) not null,
  outlook varchar(20) default 'STABLE',
  rating_date date not null,
  valid_from date,
  valid_to date,
  evaluator_id bigint unsigned,
  evaluator_name varchar(100),
  review_org_id bigint unsigned,
  review_org_name varchar(150),
  approval_no varchar(64),
  rating_status varchar(32) not null default 'DRAFT',
  key_risk_factors text,
  rating_basis text,
  rating_detail_json json,
  remark varchar(500),
  created_by bigint unsigned,
  created_by_name varchar(100),
  created_at datetime not null default current_timestamp,
  updated_by bigint unsigned,
  updated_by_name varchar(100),
  updated_at datetime not null default current_timestamp on update current_timestamp,
  deleted_flag tinyint not null default 0,
  active_customer_no varchar(32) generated always as (
    case when rating_status = 'APPROVED' and deleted_flag = 0 then customer_no_snapshot else null end
  ) stored,
  primary key (id),
  unique key uk_corporate_rating_no (rating_no),
  unique key uk_corporate_rating_active_customer (active_customer_no),
  key idx_corporate_rating_customer_date (customer_id, rating_date),
  key idx_corporate_rating_customer_no (customer_no_snapshot),
  key idx_corporate_rating_level (rating_level),
  key idx_corporate_rating_status (rating_status),
  key idx_corporate_rating_valid_to (valid_to),
  key idx_corporate_rating_tenant (tenant_id),
  constraint fk_corporate_rating_customer
    foreign key (customer_id) references corporate_customer (id),
  constraint fk_corporate_rating_customer_no
    foreign key (customer_no_snapshot) references corporate_customer (customer_no)
);
