<template>
  <section class="portfolio-page" :class="{ compact: preferenceForm.density_mode === 'COMPACT' }">
    <div class="page-toolbar">
      <div><h2>组合限额与校准</h2><p>联动行业、产品和机构集中度，持续监测 PD、LGD、EAD 偏差与预警处置成效。</p></div>
      <div class="toolbar-actions"><el-button :icon="Setting" @click="preferenceVisible=true">工作台设置</el-button><el-button :icon="Refresh" :loading="loading" @click="load">刷新</el-button><el-button type="primary" :icon="DataAnalysis" :loading="capturing" @click="capture">生成限额快照</el-button></div>
    </div>

    <section class="metric-strip">
      <div><span>组合 EAD</span><strong>{{ amount(summary.ead_amount) }}</strong><small>{{ number(summary.customer_count) }} 户 · {{ number(summary.exposure_count) }} 笔</small></div>
      <div><span>衰退预期损失</span><strong>{{ amount(summary.el_downturn_amount) }}</strong><small>平均 EL {{ amount(summary.el_avg_amount) }}</small></div>
      <div><span>行业 HHI</span><strong>{{ decimal(summary.industry_hhi, 4) }}</strong><small>组合集中度指标</small></div>
      <div><span>限额预警</span><strong class="warning">{{ number(summary.limit_warning_count) }}</strong><small>共 {{ number(summary.limit_total) }} 条限额</small></div>
      <div><span>限额超限</span><strong class="danger">{{ number(summary.limit_breach_count) }}</strong><small>需优先处置</small></div>
    </section>

    <el-tabs v-model="activeTab" class="portfolio-tabs">
      <el-tab-pane label="集中度与限额" name="limits">
        <section class="grid-two">
          <article class="panel"><div class="panel-title"><div><h3>集中度分布</h3><span>按 EAD 排序</span></div><el-select v-model="dimension" style="width:128px"><el-option label="行业" value="industry" /><el-option label="产品" value="product" /><el-option label="机构" value="organization" /></el-select></div>
            <div class="concentration-list"><div v-for="item in concentrationRows" :key="item.scope_code" class="concentration-row"><div><strong>{{ label(item.scope_name) }}</strong><small>{{ number(item.customer_count) }} 户 · {{ number(item.exposure_count) }} 笔</small></div><div class="bar-track"><div class="bar-fill" :style="{ width: concentrationWidth(item.ead_amount) }"></div></div><strong class="amount">{{ compactAmount(item.ead_amount) }}</strong></div></div>
          </article>
          <article class="panel"><div class="panel-title"><div><h3>客户集中度 Top 10</h3><span>识别单一客户暴露</span></div></div>
            <el-table :data="data.top_customers || []" size="small" max-height="300"><el-table-column prop="customer_name" label="客户" min-width="155" show-overflow-tooltip /><el-table-column label="EAD" min-width="112" align="right"><template #default="{ row }">{{ compactAmount(row.ead_amount) }}</template></el-table-column><el-table-column label="衰退 EL" min-width="105" align="right"><template #default="{ row }">{{ compactAmount(row.el_downturn_amount) }}</template></el-table-column><el-table-column prop="risk_level" label="风险" width="76" /></el-table>
          </article>
        </section>
        <article class="panel limit-panel"><div class="panel-title"><div><h3>组合风险限额</h3><span>系统基线限额可按业务授权和风险偏好调整</span></div></div>
          <el-table :data="data.limit_monitor || []" size="small" border max-height="350"><el-table-column prop="dimension_type" label="维度" width="100"><template #default="{ row }">{{ dimensionLabel(row.dimension_type) }}</template></el-table-column><el-table-column prop="scope_name" label="范围" min-width="145" show-overflow-tooltip /><el-table-column prop="metric_code" label="指标" width="92"><template #default="{ row }">{{ metricLabel(row.metric_code) }}</template></el-table-column><el-table-column label="当前值" min-width="112" align="right"><template #default="{ row }">{{ amount(row.actual_amount) }}</template></el-table-column><el-table-column label="限额" min-width="112" align="right"><template #default="{ row }">{{ amount(row.limit_amount) }}</template></el-table-column><el-table-column label="使用率" width="92" align="right"><template #default="{ row }">{{ percent(row.utilization_ratio) }}</template></el-table-column><el-table-column label="状态" width="88"><template #default="{ row }"><el-tag size="small" :type="limitType(row.monitor_status)" effect="plain">{{ limitLabel(row.monitor_status) }}</el-tag></template></el-table-column><el-table-column label="操作" width="64" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="editLimit(row)">调整</el-button></template></el-table-column></el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="限额前瞻" name="forecast">
        <article class="panel"><div class="panel-title"><div><h3>预计下月限额占用</h3><span>当前占用叠加已审批业务申请的预计支用，提前识别临界和超限</span></div></div>
          <el-table :data="(data.limit_monitor || []).filter(row => row.metric_code === 'EAD')" size="small" border max-height="480">
            <el-table-column prop="dimension_type" label="维度" width="90"><template #default="{ row }">{{ dimensionLabel(row.dimension_type) }}</template></el-table-column><el-table-column prop="scope_name" label="范围" min-width="145" show-overflow-tooltip />
            <el-table-column label="当前占用" min-width="115" align="right"><template #default="{ row }">{{ compactAmount(row.actual_amount) }}</template></el-table-column><el-table-column label="预计新增" min-width="110" align="right"><template #default="{ row }">{{ compactAmount(row.reserved_amount) }}</template></el-table-column>
            <el-table-column label="预计占用" min-width="115" align="right"><template #default="{ row }">{{ compactAmount(row.projected_amount) }}</template></el-table-column><el-table-column label="剩余空间" min-width="110" align="right"><template #default="{ row }">{{ compactAmount(row.available_amount) }}</template></el-table-column>
            <el-table-column label="预计使用率" width="105" align="right"><template #default="{ row }">{{ percent(row.forecast_utilization_ratio) }}</template></el-table-column><el-table-column label="前瞻状态" width="90"><template #default="{ row }"><el-tag size="small" :type="limitType(row.forecast_status)" effect="plain">{{ limitLabel(row.forecast_status) }}</el-tag></template></el-table-column>
          </el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="压力测试" name="stress">
        <article class="panel"><div class="panel-title"><div><h3>组合压力情景分析</h3><span>同步冲击 PD、LGD、EAD 与押品价值</span></div><div class="stress-actions"><el-select v-model="scenarioCode" style="width:180px"><el-option v-for="item in data.stress_scenarios || []" :key="item.scenario_code" :label="item.scenario_name" :value="item.scenario_code" /></el-select><el-button type="primary" :loading="stressing" @click="runStress">执行压力测试</el-button></div></div>
          <el-table :data="data.latest_stress_results || []" size="small" border max-height="480"><el-table-column prop="segment_name" label="行业" min-width="150" fixed="left" /><el-table-column prop="scenario_name" label="情景" min-width="125" /><el-table-column label="基准 EAD" min-width="110" align="right"><template #default="{ row }">{{ compactAmount(row.base_ead) }}</template></el-table-column><el-table-column label="压力 EAD" min-width="110" align="right"><template #default="{ row }">{{ compactAmount(row.stressed_ead) }}</template></el-table-column><el-table-column label="压力 PD" width="90" align="right"><template #default="{ row }">{{ percent(row.stressed_pd) }}</template></el-table-column><el-table-column label="压力 LGD" width="92" align="right"><template #default="{ row }">{{ percent(row.stressed_lgd) }}</template></el-table-column><el-table-column label="增量损失" min-width="110" align="right"><template #default="{ row }"><span class="danger">{{ compactAmount(row.incremental_loss) }}</span></template></el-table-column><el-table-column label="压力后押品" min-width="110" align="right"><template #default="{ row }">{{ compactAmount(row.stressed_collateral) }}</template></el-table-column><el-table-column label="限额" width="80"><template #default="{ row }"><el-tag size="small" :type="row.limit_breach_flag ? 'danger' : 'success'" effect="plain">{{ row.limit_breach_flag ? '突破' : '正常' }}</el-tag></template></el-table-column></el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="集团客户风险" name="groups">
        <article class="panel"><div class="panel-title"><div><h3>集团与关联客户风险聚合</h3><span>穿透成员企业、担保关系、风险敞口和集团风险偏好</span></div></div>
          <el-table :data="data.group_risk || []" size="small" border max-height="500" @row-click="openGroup"><el-table-column prop="group_name" label="集团" min-width="160" fixed="left"><template #default="{ row }"><el-link type="primary" :underline="false">{{ row.group_name }}</el-link></template></el-table-column><el-table-column prop="member_count" label="成员" width="75" align="right" /><el-table-column prop="exposure_count" label="债项" width="75" align="right" /><el-table-column label="集团 EAD" min-width="115" align="right"><template #default="{ row }">{{ compactAmount(row.ead_amount) }}</template></el-table-column><el-table-column label="衰退 EL" min-width="105" align="right"><template #default="{ row }">{{ compactAmount(row.el_downturn_amount) }}</template></el-table-column><el-table-column label="偏好使用率" width="105" align="right"><template #default="{ row }">{{ percent(row.appetite_utilization) }}</template></el-table-column><el-table-column label="押品覆盖" width="95" align="right"><template #default="{ row }">{{ percent(row.collateral_coverage) }}</template></el-table-column><el-table-column prop="overdue_count" label="逾期" width="72" align="right" /><el-table-column prop="default_count" label="违约" width="72" align="right" /><el-table-column label="状态" width="88"><template #default="{ row }"><el-tag size="small" :type="Number(row.default_count) ? 'danger' : Number(row.appetite_utilization) >= .8 ? 'warning' : 'success'" effect="plain">{{ Number(row.default_count) ? '高风险' : Number(row.appetite_utilization) >= .8 ? '关注' : '正常' }}</el-tag></template></el-table-column></el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="模型生命周期" name="lifecycle">
        <section class="metric-strip lifecycle-metrics"><div><span>模型版本</span><strong>{{ number(data.model_lifecycle_summary?.version_total) }}</strong><small>已发布 {{ number(data.model_lifecycle_summary?.published_count) }}</small></div><div><span>待审批</span><strong>{{ number(data.model_lifecycle_summary?.pending_approval_count) }}</strong><small>待发布 {{ number(data.model_lifecycle_summary?.approved_pending_publish_count) }}</small></div><div><span>需重新校准分段</span><strong class="warning">{{ number(data.model_lifecycle_summary?.recalibrate_segment_count) }}</strong><small>来自最新回溯结果</small></div><div><span>平均风险评分</span><strong>{{ decimal(data.model_lifecycle_summary?.latest_average_risk_score,2) }}</strong><small>{{ formatDate(data.model_lifecycle_summary?.latest_monitor_date) }}</small></div><div><span>当前阶段</span><strong>{{ data.model_lifecycle?.[0]?.lifecycle_stage || '-' }}</strong><small>{{ data.model_lifecycle?.[0]?.version_code || '-' }}</small></div></section>
        <article class="panel lifecycle-panel"><div class="panel-title"><div><h3>模型版本生命周期</h3><span>版本创建、模拟、提交、审批、发布与运行监控全过程</span></div></div>
          <el-table :data="data.model_lifecycle || []" size="small" border max-height="440"><el-table-column prop="version_code" label="版本" min-width="145" fixed="left" /><el-table-column prop="version_name" label="名称" min-width="160" /><el-table-column prop="lifecycle_stage" label="阶段" width="100"><template #default="{ row }"><el-tag size="small" effect="plain">{{ row.lifecycle_stage }}</el-tag></template></el-table-column><el-table-column prop="rule_count" label="规则" width="70" align="right" /><el-table-column label="模拟时间" min-width="135"><template #default="{ row }">{{ formatDate(row.simulated_at) }}</template></el-table-column><el-table-column label="审批时间" min-width="135"><template #default="{ row }">{{ formatDate(row.approved_at) }}</template></el-table-column><el-table-column label="发布时间" min-width="135"><template #default="{ row }">{{ formatDate(row.published_at) }}</template></el-table-column><el-table-column prop="approval_action_count" label="审计动作" width="90" align="right" /></el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="PD/LGD/EAD 回溯" name="backtest">
        <article class="panel"><div class="panel-title"><div><h3>模型回溯与校准</h3><span>比较预期 PD/LGD、预测违约 EAD 与实际违约表现</span></div><el-button type="primary" :icon="TrendCharts" :loading="backtesting" @click="runBacktest">执行回溯</el-button></div>
          <el-table :data="data.latest_backtest || []" size="small" border max-height="470"><el-table-column prop="segment_type" label="分段维度" width="100"><template #default="{ row }">{{ dimensionLabel(row.segment_type) }}</template></el-table-column><el-table-column prop="segment_name" label="分段" min-width="140" /><el-table-column label="预期 PD" width="92" align="right"><template #default="{ row }">{{ percent(row.expected_pd) }}</template></el-table-column><el-table-column label="实际违约率" width="102" align="right"><template #default="{ row }">{{ percent(row.observed_default_rate) }}</template></el-table-column><el-table-column label="预期 LGD" width="92" align="right"><template #default="{ row }">{{ percent(row.expected_lgd) }}</template></el-table-column><el-table-column label="实际 LGD" width="92" align="right"><template #default="{ row }">{{ percent(row.observed_lgd) }}</template></el-table-column><el-table-column label="EAD 偏差" width="92" align="right"><template #default="{ row }">{{ signedPercent(row.ead_bias) }}</template></el-table-column><el-table-column label="状态" width="96"><template #default="{ row }"><el-tag size="small" :type="calibrationType(row.calibration_status)" effect="plain">{{ calibrationLabel(row.calibration_status) }}</el-tag></template></el-table-column><el-table-column prop="recommendation" label="校准建议" min-width="220" show-overflow-tooltip /></el-table>
        </article>
      </el-tab-pane>

      <el-tab-pane label="预警处置效果" name="effectiveness">
        <section class="effect-metrics"><div><span>已评价</span><strong>{{ number(data.effectiveness_metrics?.evaluated_count) }}</strong></div><div><span>有效率</span><strong>{{ percent(data.effectiveness_metrics?.effective_rate) }}</strong></div><div><span>风险改善率</span><strong>{{ percent(data.effectiveness_metrics?.improvement_rate) }}</strong></div><div><span>无效率</span><strong class="danger">{{ percent(data.effectiveness_metrics?.ineffective_rate) }}</strong></div><div><span>平均评分改善</span><strong>{{ decimal(data.effectiveness_metrics?.average_score_improvement,2) }}</strong></div></section>
        <article class="panel"><div class="panel-title"><div><h3>处置效果评价</h3><span>关闭后以 30 天为观察窗口，对比案件基线与当前风险表现</span></div><el-button type="primary" :icon="CircleCheck" :loading="evaluating" @click="runEffectiveness">生成评价</el-button></div>
          <el-table :data="data.latest_effectiveness || []" size="small" border max-height="470"><el-table-column prop="customer_no" label="客户编号" min-width="145" /><el-table-column label="关闭时间" min-width="132"><template #default="{ row }">{{ formatDate(row.closed_at) }}</template></el-table-column><el-table-column label="评分变化" width="100" align="right"><template #default="{ row }">{{ number(row.baseline_risk_score) }} → {{ number(row.current_risk_score) }}</template></el-table-column><el-table-column label="当前 PD" width="90" align="right"><template #default="{ row }">{{ percent(row.current_pd) }}</template></el-table-column><el-table-column label="衰退 LGD" width="92" align="right"><template #default="{ row }">{{ percent(row.current_lgd_downturn) }}</template></el-table-column><el-table-column label="逾期/违约" width="96" align="right"><template #default="{ row }">{{ number(row.overdue_count) }}/{{ number(row.debt_default_count) }}</template></el-table-column><el-table-column label="评价" width="104"><template #default="{ row }"><el-tag size="small" :type="effectType(row.effectiveness_status)" effect="plain">{{ effectLabel(row.effectiveness_status) }}</el-tag></template></el-table-column><el-table-column prop="conclusion" label="结论" min-width="260" show-overflow-tooltip /></el-table>
        </article>
      </el-tab-pane>
    </el-tabs>

    <el-dialog v-model="limitVisible" title="调整组合风险限额" width="460px"><el-form :model="limitForm" label-width="90px"><el-form-item label="范围"><el-input v-model="limitForm.scope_name" disabled /></el-form-item><el-form-item label="指标"><el-input v-model="limitForm.metric_code" disabled /></el-form-item><el-form-item label="限额"><el-input-number v-model="limitForm.limit_amount" :min="1" :precision="2" :step="100000" controls-position="right" /></el-form-item><el-form-item label="预警比例"><el-input-number v-model="limitForm.warning_ratio" :min="0.01" :max="1" :precision="2" :step="0.05" controls-position="right" /></el-form-item><el-form-item label="责任人"><el-input v-model="limitForm.owner" /></el-form-item><el-form-item label="状态"><el-switch v-model="limitForm.enabled" active-text="启用" inactive-text="停用" /></el-form-item></el-form><template #footer><el-button @click="limitVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveLimit">保存</el-button></template></el-dialog>
    <el-dialog v-model="preferenceVisible" title="个性工作台设置" width="500px"><el-form label-width="100px"><el-form-item label="工作角色"><el-select v-model="preferenceForm.workspace_role" style="width:100%"><el-option label="风险经理" value="RISK_MANAGER" /><el-option label="管理层" value="EXECUTIVE" /><el-option label="模型人员" value="MODEL_ANALYST" /></el-select></el-form-item><el-form-item label="默认页面"><el-select v-model="preferenceForm.default_tab" style="width:100%"><el-option label="集中度与限额" value="limits" /><el-option label="限额前瞻" value="forecast" /><el-option label="压力测试" value="stress" /><el-option label="集团客户风险" value="groups" /><el-option label="模型生命周期" value="lifecycle" /><el-option label="模型回溯" value="backtest" /><el-option label="预警效果" value="effectiveness" /></el-select></el-form-item><el-form-item label="显示密度"><el-segmented v-model="preferenceForm.density_mode" :options="[{label:'舒适',value:'COMFORTABLE'},{label:'紧凑',value:'COMPACT'}]" /></el-form-item></el-form><template #footer><el-button @click="preferenceVisible=false">取消</el-button><el-button type="primary" :loading="preferenceSaving" @click="savePreference">保存设置</el-button></template></el-dialog>
    <el-drawer v-model="groupVisible" size="min(820px,100%)" :title="selectedGroup?.group_name || '集团成员明细'">
      <el-table v-loading="groupLoading" :data="groupMembers" size="small" border><el-table-column prop="customer_name" label="成员客户" min-width="180" show-overflow-tooltip /><el-table-column prop="relationship_type" label="关系" width="105" /><el-table-column label="持股比例" width="92" align="right"><template #default="{ row }">{{ percent(row.ownership_ratio) }}</template></el-table-column><el-table-column label="担保" width="70"><template #default="{ row }">{{ row.guarantee_flag ? '是' : '否' }}</template></el-table-column><el-table-column label="EAD" min-width="105" align="right"><template #default="{ row }">{{ compactAmount(row.ead_amount) }}</template></el-table-column><el-table-column prop="overdue_count" label="逾期" width="70" align="right" /><el-table-column prop="default_count" label="违约" width="70" align="right" /></el-table>
    </el-drawer>
  </section>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { CircleCheck, DataAnalysis, Refresh, Setting, TrendCharts } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import http from '../api/http'

const data = ref({})
const loading = ref(false), capturing = ref(false), backtesting = ref(false), evaluating = ref(false), saving = ref(false), stressing = ref(false)
const activeTab = ref('limits'), dimension = ref('industry'), limitVisible = ref(false)
const scenarioCode = ref('MILD_DOWNTURN'), groupVisible = ref(false), groupLoading = ref(false), selectedGroup = ref(null), groupMembers = ref([])
const preferenceVisible = ref(false), preferenceSaving = ref(false)
const preferenceForm = reactive({ workspace_role: 'RISK_MANAGER', default_tab: 'limits', density_mode: 'COMFORTABLE' })
const limitForm = reactive({ id: null, scope_name: '', metric_code: '', limit_amount: 0, warning_ratio: 0.8, owner: '', enabled: true })
const summary = computed(() => data.value.summary || {})
const concentrationRows = computed(() => data.value[`${dimension.value}_concentration`] || [])
onMounted(load)
async function load() { loading.value = true; try { data.value = await http.get('/api/risks/portfolio-management'); const preference=data.value.workbench_preference; if(preference){Object.assign(preferenceForm,{workspace_role:preference.workspace_role||'RISK_MANAGER',default_tab:preference.default_tab||'limits',density_mode:preference.density_mode||'COMFORTABLE'}); activeTab.value=preferenceForm.default_tab} } finally { loading.value = false } }
async function capture() { capturing.value = true; try { await http.post('/api/risks/portfolio-management/limit-snapshots'); await load() } finally { capturing.value = false } }
async function runBacktest() { backtesting.value = true; try { const result = await http.post('/api/risks/portfolio-management/backtests'); data.value.latest_backtest = result.results || []; activeTab.value = 'backtest' } finally { backtesting.value = false } }
async function runEffectiveness() { evaluating.value = true; try { const result = await http.post('/api/risks/portfolio-management/alert-effectiveness'); data.value.latest_effectiveness = result.results || []; activeTab.value = 'effectiveness' } finally { evaluating.value = false } }
async function runStress() { stressing.value = true; try { const result = await http.post('/api/risks/portfolio-management/stress-tests', { scenario_code: scenarioCode.value }); data.value.latest_stress_results = result.results || []; activeTab.value = 'stress' } finally { stressing.value = false } }
async function openGroup(row) { selectedGroup.value = row; groupVisible.value = true; groupLoading.value = true; try { const result = await http.get(`/api/risks/portfolio-management/groups/${encodeURIComponent(row.group_code)}/members`); groupMembers.value = result.members || [] } finally { groupLoading.value = false } }
async function savePreference() { preferenceSaving.value=true; try { await http.put('/api/risks/portfolio-management/workbench-preference',{...preferenceForm,visible_modules:['limits','forecast','stress','groups','lifecycle','backtest','effectiveness']}); activeTab.value=preferenceForm.default_tab; preferenceVisible.value=false; ElMessage.success('工作台设置已保存') } finally { preferenceSaving.value=false } }
function editLimit(row) { Object.assign(limitForm, { id: row.id, scope_name: row.scope_name, metric_code: metricLabel(row.metric_code), limit_amount: Number(row.limit_amount), warning_ratio: Number(row.warning_ratio), owner: row.owner || '', enabled: row.status === 'ENABLED' }); limitVisible.value = true }
async function saveLimit() { saving.value = true; try { const result = await http.put(`/api/risks/portfolio-management/limits/${limitForm.id}`, { limit_amount: limitForm.limit_amount, warning_ratio: limitForm.warning_ratio, owner: limitForm.owner, status: limitForm.enabled ? 'ENABLED' : 'DISABLED' }); data.value.limit_monitor = result.limit_monitor || []; data.value.summary = { ...(data.value.summary || {}), ...(result.summary || {}) }; limitVisible.value = false } finally { saving.value = false } }
function number(value) { return Number(value || 0).toLocaleString('zh-CN') }
function decimal(value, digits = 2) { return Number(value || 0).toFixed(digits) }
function amount(value) { return `¥${Number(value || 0).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` }
function compactAmount(value) { const v = Number(value || 0); return v >= 100000000 ? `¥${(v / 100000000).toFixed(2)}亿` : v >= 10000 ? `¥${(v / 10000).toFixed(2)}万` : amount(v) }
function percent(value) { return `${(Number(value || 0) * 100).toFixed(2)}%` }
function signedPercent(value) { const v = Number(value || 0); return `${v >= 0 ? '+' : ''}${(v * 100).toFixed(2)}%` }
function formatDate(value) { return value ? String(value).replace('T', ' ').slice(0, 16) : '-' }
function label(value) { return value || '-' }
function concentrationWidth(value) { const max = Math.max(...concentrationRows.value.map((item) => Number(item.ead_amount || 0)), 1); return `${Math.max(5, Number(value || 0) / max * 100)}%` }
function dimensionLabel(value) { return ({ INDUSTRY: '行业', PRODUCT: '产品', ORGANIZATION: '机构' })[value] || value }
function metricLabel(value) { return ({ EAD: 'EAD', EL_DOWN: '衰退 EL' })[value] || value }
function limitType(value) { return ({ BREACH: 'danger', WARNING: 'warning', NORMAL: 'success', DISABLED: 'info' })[value] || 'info' }
function limitLabel(value) { return ({ BREACH: '超限', WARNING: '预警', NORMAL: '正常', DISABLED: '停用' })[value] || value }
function calibrationType(value) { return ({ RECALIBRATE: 'danger', WATCH: 'warning', STABLE: 'success' })[value] || 'info' }
function calibrationLabel(value) { return ({ RECALIBRATE: '需校准', WATCH: '关注', STABLE: '稳定' })[value] || value }
function effectType(value) { return ({ EFFECTIVE: 'success', PARTIAL: 'warning', INEFFECTIVE: 'danger', OBSERVING: 'info' })[value] || 'info' }
function effectLabel(value) { return ({ EFFECTIVE: '有效', PARTIAL: '部分有效', INEFFECTIVE: '无效', OBSERVING: '观察中' })[value] || value }
</script>

<style scoped>
.portfolio-page { display: grid; gap: 16px; }.page-toolbar,.toolbar-actions,.panel-title { display:flex;align-items:center;justify-content:space-between;gap:12px; }h2,h3,p{margin:0}h2{color:#1f2937;font-size:18px;font-weight:650}.page-toolbar p,.panel-title span{color:#64748b;font-size:13px;margin-top:5px}.metric-strip{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));background:#fff;border:1px solid #dce4ee;border-radius:8px;overflow:hidden}.metric-strip>div{display:grid;gap:5px;padding:14px;min-height:88px;border-right:1px solid #e8eef4}.metric-strip>div:last-child{border-right:0}.metric-strip span,.metric-strip small{color:#64748b;font-size:12px}.metric-strip strong{color:#1f2937;font-size:19px}.warning{color:#b45309!important}.danger{color:#c2413a!important}.portfolio-tabs :deep(.el-tabs__header){margin-bottom:12px}.grid-two{display:grid;grid-template-columns:minmax(0,1fr) minmax(360px,.9fr);gap:16px}.panel{padding:16px}.panel-title{margin-bottom:13px}.panel-title h3{color:#334155;font-size:15px}.concentration-list{display:grid;gap:13px}.concentration-row{display:grid;grid-template-columns:165px minmax(110px,1fr) 96px;align-items:center;gap:10px}.concentration-row>div:first-child{display:grid;gap:3px}.concentration-row small{color:#64748b;font-size:11px}.concentration-row strong{color:#334155;font-size:13px}.bar-track{height:12px;background:#edf2f6;overflow:hidden}.bar-fill{height:100%;background:#3d739c}.amount{text-align:right}.limit-panel{margin-top:16px}@media(max-width:1050px){.metric-strip{grid-template-columns:repeat(3,minmax(0,1fr))}.metric-strip>div:nth-child(3n){border-right:0}.metric-strip>div:nth-child(-n+3){border-bottom:1px solid #e8eef4}.grid-two{grid-template-columns:1fr}}@media(max-width:640px){.page-toolbar,.panel-title{align-items:flex-start;flex-direction:column}.toolbar-actions{width:100%}.toolbar-actions .el-button{flex:1}.metric-strip{grid-template-columns:1fr}.metric-strip>div{border-right:0;border-bottom:1px solid #e8eef4}.metric-strip>div:last-child{border-bottom:0}.concentration-row{grid-template-columns:1fr}.amount{text-align:left}}
.stress-actions{display:flex;align-items:center;gap:10px}
.effect-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));margin-bottom:14px;background:#fff;border:1px solid #dce4ee;border-radius:8px;overflow:hidden}.effect-metrics>div{display:grid;gap:5px;padding:13px;border-right:1px solid #e8eef4}.effect-metrics>div:last-child{border-right:0}.effect-metrics span{color:#64748b;font-size:12px}.effect-metrics strong{color:#1f2937;font-size:18px}.lifecycle-metrics{margin-bottom:14px}.lifecycle-panel{margin-top:0}.portfolio-page.compact .panel{padding:12px}.portfolio-page.compact :deep(.el-table .cell){padding-left:7px;padding-right:7px}@media(max-width:800px){.effect-metrics{grid-template-columns:1fr}.effect-metrics>div{border-right:0;border-bottom:1px solid #e8eef4}.stress-actions{width:100%;flex-wrap:wrap}}
</style>
